# -*- coding: utf-8 -*-
"""
BAM -> BED stage deploy -- the analysis step that runs AFTER STAR on the cluster.

When the analysis module is "bulk_rna_seq" and the cluster is on, this fills the vendored
bed_template/ config.sh from the form + the STAR run, ships it (INCLUDING the vendored AltAnalyze
toolkit under altanalyze/) to <BAM_OUT>/bed, and AUTO-CHAINS it: a launcher job (bed_launch.sh) waits
for STAR's PIPELINE_COMPLETE.txt, then runs ./run_bed_pipeline.sh, which converts each STAR BAM to
<sample>__junction.bed + <sample>__exon.bed (AltAnalyze junction/exon BEDs).

ALL-IN-ONE: the AltAnalyze BAMto*BED.py scripts + export.py/unique.py helpers + the exon reference are
VENDORED in bed_template/altanalyze/ and shipped with the bundle, so the cluster needs NO AltAnalyze
install -- only the stock python/2.7.5 (which provides pysam) and samtools modules. The ~100 MB exon
reference is uploaded SEPARATELY and idempotently (size-skip) so it is not re-pushed every run.

Reuses cluster_deploy's fill_config / SSH transport / diagnose_failure.
"""
import os
import re
import shutil
import subprocess

from progress import NULL
import cluster_deploy
import star_deploy   # reuse detect_organism (organism consistency across the two stages)

HERE = os.path.dirname(os.path.abspath(__file__))
BED_TEMPLATE_DIR = os.path.join(HERE, "bed_template")

# config.sh vars we fill (name -> default). Numerics are written unquoted.
BED_CONFIG_DEFAULTS = {
    "BAM_INPUT_DIR": "/data/CHANGE_ME/STAR_bams",
    "ALTANALYZE_DIR": "",          # "" => config.sh derives $SCRIPTS_DIR/altanalyze (the vendored copy)
    "ORGANISM": "Homo sapiens",
    "SPECIES": "",                 # "" => config.sh derives from ORGANISM (default Hs)
    "EXON_REF": "",                # "" => config.sh derives from ALTANALYZE_DIR + SPECIES
    "BED_MODE": "intron",          # intron (default) | exon | both -- which BAMtoExonBED pass(es)
    "DELETE_BAM_AFTER_BED": "0",    # UI toggle: delete each BAM once its BEDs are made+verified (default OFF)
    "THREADS": 1,                  # BAMtoBED is a single Python process; 1 slot packs the node
    "MEM_MB": 32000,
    "WALL": "1108:00",   # default -W: queue MAX (66480 min) so deep-BAM bed jobs never die to walltime
    "LSF_QUEUE": "",
    "JOB_TAG": "bed",
    "WATCHDOG_INTERVAL_MIN": 30,
    "MAX_STALL_PASSES": 2,
    "PYTHON_MODULE": "python/2.7.5",   # supplies python2 AND pysam
    "SAMTOOLS_MODULE": "samtools",
}
BED_NUMERIC = {"THREADS", "MEM_MB", "WATCHDOG_INTERVAL_MIN", "MAX_STALL_PASSES"}

# ORGANISM (NCBI scientific name) -> AltAnalyze species code. Default Hs.
_SPECIES_MAP = {
    "homo sapiens": "Hs", "mus musculus": "Mm", "rattus norvegicus": "Rn",
    "danio rerio": "Dr", "sus scrofa": "Ss", "macaca": "Ma",
}


def organism_to_species(organism):
    key = " ".join((organism or "").lower().split())
    if key in _SPECIES_MAP:
        return _SPECIES_MAP[key]
    for k, v in _SPECIES_MAP.items():     # prefix match ("Macaca mulatta", etc.)
        if key.startswith(k):
            return v
    return "Hs"


def _resolve_bed_cfg(bed_cfg):
    vals = dict(BED_CONFIG_DEFAULTS)
    for k in BED_CONFIG_DEFAULTS:
        if bed_cfg and k in bed_cfg and str(bed_cfg[k]).strip() != "":
            vals[k] = bed_cfg[k]
    return vals


def _bed_launch_sh(bam_out_root, bed_tag, check_min=30, max_wait_hours=168):
    """SELF-RESCHEDULING launcher (mirrors star_launch.sh). Each pass is a short LSF job: if STAR has
    finished it launches BED, otherwise it re-queues itself for +CHECK_MIN. Lives entirely on the
    cluster, so SpliceScout can be CLOSED right after the upload.

    Hardening (mirrors star_launch.sh): if STAR finalized STALLED (not COMPLETE), BED still converts
    whatever aligned, but the BED root is marked PIPELINE_INCOMPLETE_UPSTREAM.txt so BED's finalize
    disables destructive cleanup + BAM deletion and reports an HONEST partial result. Bounded wait:
    give up (PIPELINE_LAUNCH_TIMEOUT.txt) only after MAX_WAIT_HOURS *and* a stale STAR watchdog.log."""
    bo = bam_out_root.rstrip("/")
    return (
        "#!/usr/bin/env bash\n"
        "# bed_launch.sh -- generated by SpliceScout. Self-rescheduling: checks if STAR finished; if so\n"
        "# launches BAM->BED (AltAnalyze junction/exon), else re-queues itself. Runs as short LSF jobs.\n"
        'HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"\n'
        f"BAM_OUT={cluster_deploy.shq(bo)}\n"
        f"CHECK_MIN={int(check_min)}\n"
        f"MAX_WAIT_HOURS={int(max_wait_hours)}\n"
        f"JT={cluster_deploy.shq(bed_tag)}\n"
        "command -v bsub >/dev/null 2>&1 || { echo '[bed_launch] no bsub here' >&2; exit 0; }\n"
        "# BED already finished -> nothing to do\n"
        'if [ -f "$BAM_OUT/bed/PIPELINE_COMPLETE.txt" ] || [ -f "$BAM_OUT/bed/PIPELINE_STALLED.txt" ]; then\n'
        '  echo "[bed_launch] BED already finalized -> stop"; exit 0\n'
        "fi\n"
        "# STAR finished (or stalled -> BED whatever aligned) -> TRY to launch. On failure, fall through to\n"
        "# reschedule + retry (run_bed_pipeline.sh is idempotent). Stop only on success.\n"
        'if [ -f "$BAM_OUT/PIPELINE_COMPLETE.txt" ] || [ -f "$BAM_OUT/PIPELINE_STALLED.txt" ]; then\n'
        "  # STAR STALLED (not COMPLETE) -> this BED run is PARTIAL: mark it so BED finalize keeps the BAMs\n"
        "  # (no deletion) and skips destructive tool cleanup, and reports honestly.\n"
        '  if [ ! -f "$BAM_OUT/PIPELINE_COMPLETE.txt" ] && [ -f "$BAM_OUT/PIPELINE_STALLED.txt" ]; then\n'
        '    mkdir -p "$BAM_OUT/bed" 2>/dev/null\n'
        '    { echo "upstream STAR STALLED at $(date) -- not all samples aligned."; \\\n'
        '      echo "This BED run is PARTIAL: destructive cleanup + BAM deletion are DISABLED."; } \\\n'
        '      > "$BAM_OUT/bed/PIPELINE_INCOMPLETE_UPSTREAM.txt" 2>/dev/null\n'
        '    cp -f "$BAM_OUT/PIPELINE_STALLED.txt" "$BAM_OUT/bed/UPSTREAM_STAR_STALLED.txt" 2>/dev/null\n'
        "  fi\n"
        '  echo "[bed_launch] STAR finished -> launching BED pipeline"\n'
        '  if bash "$HERE/run_bed_pipeline.sh"; then\n'
        '    echo "[bed_launch] BED pipeline launched -> stop"; exit 0\n'
        "  fi\n"
        '  echo "[bed_launch] run_bed_pipeline.sh FAILED -> will retry in $CHECK_MIN min" >&2\n'
        "fi\n"
        "# Bounded wait: abort only if past MAX_WAIT_HOURS AND STAR's watchdog.log is stale (dead chain).\n"
        'STAMP="$HERE/.launch_first_seen"\n'
        '[ -f "$STAMP" ] || date +%s > "$STAMP" 2>/dev/null\n'
        'now=$(date +%s); first=$(cat "$STAMP" 2>/dev/null || echo "$now")\n'
        'upwd="$BAM_OUT/watchdog.log"; up_age=999999999\n'
        '[ -f "$upwd" ] && up_age=$(( now - $(stat -c %Y "$upwd" 2>/dev/null || echo "$now") ))\n'
        'if [ "$(( now - first ))" -gt "$(( MAX_WAIT_HOURS * 3600 ))" ] && [ "$up_age" -gt "$(( CHECK_MIN * 180 ))" ]; then\n'
        '  mkdir -p "$BAM_OUT/bed" 2>/dev/null\n'
        '  echo "BED launcher gave up at $(date): STAR never finalized and its watchdog.log went stale (>${MAX_WAIT_HOURS}h)." \\\n'
        '    > "$BAM_OUT/bed/PIPELINE_LAUNCH_TIMEOUT.txt" 2>/dev/null\n'
        '  echo "[bed_launch] upstream dead -> giving up (PIPELINE_LAUNCH_TIMEOUT.txt written)" >&2; exit 0\n'
        "fi\n"
        "when=$(date -d \"+$CHECK_MIN min\" '+%Y:%m:%d:%H:%M' 2>/dev/null) || "
        "when=$(date -v+\"${CHECK_MIN}\"M '+%Y:%m:%d:%H:%M' 2>/dev/null)\n"
        'bsub -L /bin/bash -n 1 -M 1000 -W 66480 -b "$when" -J "${JT}_launch" \\\n'
        '     -o "$BAM_OUT/bed/launch.out" -e "$BAM_OUT/bed/launch.err" \\\n'
        '     "$HERE/bed_launch.sh" >/dev/null 2>&1\n'
        'echo "[bed_launch] not done / will retry -> next check scheduled for $when"\n'
    )


def _copy_lf(srcf, destf):
    txt = open(srcf, encoding="utf-8", errors="replace").read().replace("\r\n", "\n").replace("\r", "\n")
    with open(destf, "w", encoding="utf-8", newline="\n") as f:
        f.write(txt)


def _write_bed_instructions(P, vals, bam_out_root):
    txt = (
        "BAM -> BED bundle (AltAnalyze junction/exon; Bulk RNA-seq module)\n"
        "================================================================\n"
        f"Reads BAMs from : {vals['BAM_INPUT_DIR']}\n"
        f"Writes BEDs to  : {os.path.dirname(vals['BAM_INPUT_DIR'].rstrip('/'))}/STAR_beds  (kept SEPARATE from the BAMs)\n"
        f"BED mode        : {vals.get('BED_MODE', 'intron')}  "
        "(intron=>__intronJunction.bed, exon=>__exon.bed, both=>both)\n"
        f"Species         : {vals['SPECIES']}  (organism {vals['ORGANISM']})\n"
        "AltAnalyze      : VENDORED in altanalyze/ (no cluster install needed; uses python/2.7.5 + samtools)\n\n"
        "Autonomous mode launches this automatically AFTER STAR finishes. To run it manually:\n"
        f"  cd {bam_out_root.rstrip('/')}/bed\n"
        "  chmod +x *.sh\n"
        "  ./run_bed_pipeline.sh\n"
        "Watch:  bash status.sh   (or tail -f <BAM_OUT>/bed/watchdog.log)\n"
        "Done when <BAM_OUT>/bed/PIPELINE_COMPLETE.txt appears.\n"
    )
    with open(os.path.join(P.bed_dir, "RUN_BED_ON_CLUSTER.txt"), "w", encoding="utf-8", newline="\n") as f:
        f.write(txt)


def build_bed_bundle(P, sel, bam_out_root, bed_cfg, star_job_tag="sra_star", reporter=NULL):
    """Assemble runtable/bed/ (filled config.sh + vendored scripts + altanalyze/ toolkit + launcher),
    zip it, and return a summary. The big exon reference is left OUT of the bundle (uploaded separately,
    idempotently, by submit_bed_over_ssh). Returns None if the template is missing."""
    if not os.path.isdir(BED_TEMPLATE_DIR):
        print(f"  BED BUNDLE: vendored template missing at {BED_TEMPLATE_DIR} -> skipping")
        return None
    reporter.set_detail("assembling BED bundle…")
    if os.path.isdir(P.bed_dir):
        shutil.rmtree(P.bed_dir, ignore_errors=True)
    os.makedirs(P.bed_dir, exist_ok=True)

    # top-level scripts (LF), everything except config.sh (generated)
    for name in sorted(os.listdir(BED_TEMPLATE_DIR)):
        srcf = os.path.join(BED_TEMPLATE_DIR, name)
        if os.path.isfile(srcf) and name != "config.sh":
            _copy_lf(srcf, os.path.join(P.bed_dir, name))

    # vendored altanalyze/ subtree EXCEPT refs/ (the ~100 MB exon ref ships via the idempotent upload)
    aa_src = os.path.join(BED_TEMPLATE_DIR, "altanalyze")
    if os.path.isdir(aa_src):
        for base, dirs, files in os.walk(aa_src):
            if os.path.relpath(base, aa_src) == ".":
                dirs[:] = [d for d in dirs if d != "refs"]   # prune the heavy reference tree
            rel = os.path.relpath(base, BED_TEMPLATE_DIR)
            dest_base = os.path.join(P.bed_dir, rel)
            os.makedirs(dest_base, exist_ok=True)
            for fn in files:
                sp = os.path.join(base, fn)
                dp = os.path.join(dest_base, fn)
                if fn.endswith((".py", ".sh", ".txt", ".json", ".md")):
                    _copy_lf(sp, dp)
                else:
                    shutil.copyfile(sp, dp)

    organism = star_deploy.detect_organism(P, sel, (bed_cfg or {}).get("ORGANISM"))
    bo = bam_out_root.rstrip("/")
    bed_root = f"{bo}/bed"

    vals = _resolve_bed_cfg(bed_cfg)
    vals["BAM_INPUT_DIR"] = bo
    vals["ALTANALYZE_DIR"] = ""     # config.sh derives the vendored $SCRIPTS_DIR/altanalyze
    vals["EXON_REF"] = ""           # config.sh derives from ALTANALYZE_DIR + SPECIES
    vals["ORGANISM"] = organism
    vals["SPECIES"] = (bed_cfg or {}).get("SPECIES") or organism_to_species(organism)
    vals["JOB_TAG"] = f"{(star_job_tag or 'sra_star')}_bed"
    _mode = str(vals.get("BED_MODE", "")).strip().lower()
    vals["BED_MODE"] = _mode if _mode in ("intron", "exon", "both") else "intron"

    vals["ALERT_EMAIL"] = vals.get("ALERT_EMAIL") or cluster_deploy._alert_email()   # cluster-side email
    cluster_deploy.bake_diagnose_model(vals)                                         # optional diagnose-AI model path / cache dir
    template = open(os.path.join(BED_TEMPLATE_DIR, "config.sh"), encoding="utf-8").read()
    with open(os.path.join(P.bed_dir, "config.sh"), "w", encoding="utf-8", newline="\n") as f:
        f.write(cluster_deploy.fill_config(template, vals, numeric=BED_NUMERIC, defaults=BED_CONFIG_DEFAULTS))
    with open(os.path.join(P.bed_dir, "bed_launch.sh"), "w", encoding="utf-8", newline="\n") as f:
        f.write(_bed_launch_sh(bam_out_root, vals["JOB_TAG"]))

    _write_bed_instructions(P, vals, bam_out_root)
    cluster_deploy._zip_dir(P.bed_dir, P.bed_bundle_zip)
    print(f"  BED BUNDLE: species={vals['SPECIES']!r} (organism={organism!r}) mode={vals['BED_MODE']} "
          f"tag={vals['JOB_TAG']} -> {os.path.basename(P.bed_bundle_zip)}")
    reporter.set_detail(f"BED bundle ready (species {vals['SPECIES']}, mode {vals['BED_MODE']})")
    return {"bam_input": bo, "bed_out": bo, "job_tag": vals["JOB_TAG"],
            "species": vals["SPECIES"], "organism": organism, "bed_mode": vals["BED_MODE"],
            "bed_root": bed_root}


def _read_bundle_species(P):
    cfgsh = os.path.join(P.bed_dir, "config.sh")
    try:
        m = re.search(r'(?m)^SPECIES="?(.*?)"?\s*$', open(cfgsh, encoding="utf-8").read())
        if m and m.group(1).strip():
            return m.group(1).strip()
    except Exception:
        pass
    return "Hs"


def _upload_ref_idempotent(host, port, user, keyfile, password, bed_root, species, reporter):
    """Upload the vendored exon reference to <bed_root>/altanalyze/refs/<SP>/ -- but SKIP if a file of
    the same byte size already exists there (so the ~100 MB ref isn't re-pushed every run)."""
    local = os.path.join(BED_TEMPLATE_DIR, "altanalyze", "refs", species, f"{species}_Ensembl_exon.txt")
    if not os.path.exists(local):
        # the exon ref ships gzip'd in git; if only the .gz is present (a fresh clone that never launched
        # the UI), expand it now so a standalone deploy still finds the plain-text reference.
        try:
            import ensure_refs
            ensure_refs.ensure_ref_files()
        except Exception:
            pass
    if not os.path.exists(local):
        print(f"  BED SUBMIT: no vendored exon ref for species {species!r} ({local}) -> NOT uploading "
              "(the cluster setup.sh will flag a missing EXON_REF)")
        return
    remote = f"{bed_root}/altanalyze/refs/{species}/{species}_Ensembl_exon.txt"
    rdir = f"{bed_root}/altanalyze/refs/{species}"
    lsize = os.path.getsize(local)
    lmb = lsize // 1048576

    if password:
        import paramiko
        cli = paramiko.SSHClient()
        cli.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        kw = {"hostname": host, "port": int(port), "username": user, "timeout": 20}
        if password:
            kw["password"] = password
        if keyfile:
            kw["key_filename"] = keyfile
        cli.connect(**kw)
        try:
            sftp = cli.open_sftp()
            sftp.get_channel().settimeout(600)   # ~100 MB exon-ref put can't hang the worker forever
            try:
                rsize = sftp.stat(remote).st_size
            except Exception:
                rsize = -1
            if rsize == lsize:
                print(f"  BED SUBMIT: exon ref already present on cluster ({lsize} bytes) -> skip upload")
            else:
                _i, _o, _e = cli.exec_command(f"mkdir -p {cluster_deploy.shq(rdir)}", timeout=600)
                _o.channel.settimeout(60)   # cap the exit-status wait so a stalled network can't hang
                _o.channel.recv_exit_status()
                reporter.set_detail(f"uploading {species} exon ref (~{lmb} MB)…")
                sftp.put(local, remote)
                print(f"  BED SUBMIT: uploaded exon ref ({lmb} MB) -> {remote}")
            sftp.close()
        finally:
            cli.close()
        return

    target = f"{user}@{host}"
    common = ["-o", "BatchMode=yes", "-o", "StrictHostKeyChecking=accept-new", "-o", "ConnectTimeout=20"]
    ssh = ["ssh", "-p", str(port)] + common + (["-i", keyfile] if keyfile else [])
    scp = ["scp", "-P", str(port)] + common + (["-i", keyfile] if keyfile else [])
    try:
        r = subprocess.run(ssh + [target, f"stat -c %s {cluster_deploy.shq(remote)} 2>/dev/null || echo 0"],
                           capture_output=True, text=True, timeout=60)
        rsize = int((r.stdout or "0").strip() or 0)
    except Exception:
        rsize = 0
    if rsize == lsize:
        print(f"  BED SUBMIT: exon ref already present on cluster ({lsize} bytes) -> skip upload")
        return
    cluster_deploy._run(ssh + [target, f"mkdir -p {cluster_deploy.shq(rdir)}"])
    reporter.set_detail(f"uploading {species} exon ref (~{lmb} MB)…")
    cluster_deploy._run(scp + [local, f"{target}:{remote}"], timeout=1800)
    print(f"  BED SUBMIT: uploaded exon ref ({lmb} MB) -> {remote}")


def submit_bed_over_ssh(P, cluster_cfg, secrets, bam_out_root, reporter=NULL, prior_skipped=False):
    """Upload the BED bundle (+ idempotent exon ref) and submit the auto-chain launcher (waits on STAR).
    Non-fatal. prior_skipped=True (phase-range START at BAM->BED): STAR was skipped, so pre-create the
    <BAM_OUT>/PIPELINE_COMPLETE.txt sentinel the launcher polls -> BED runs immediately on existing BAMs."""
    cfg = cluster_cfg or {}
    secrets = secrets or {}
    host = (cfg.get("ssh_host") or "").strip()
    user = (cfg.get("ssh_user") or "").strip()
    port = str(cfg.get("ssh_port") or "22").strip() or "22"
    keyfile = (cfg.get("ssh_key") or "").strip()
    password = secrets.get("ssh_password") or ""
    dl_tag = (cfg.get("JOB_TAG") or "sra").strip() or "sra"
    bed_tag = f"{dl_tag}_star_bed"
    bed_root = f"{bam_out_root.rstrip('/')}/bed"

    if not host or not user:
        print("  BED SUBMIT: missing SSH host/user -> bundle still downloadable")
        return {"submitted": False, "reason": "missing host/user",
                "diagnosis": cluster_deploy.diagnose_failure("missing host/user")}
    if not os.path.isdir(P.bed_dir):
        return {"submitted": False, "reason": "no bundle",
                "diagnosis": cluster_deploy.diagnose_failure("", "no bundle")}

    species = _read_bundle_species(P)
    shq = cluster_deploy.shq
    # DETACH the launcher bsub (setsid, backgrounded in a subshell so only the bsub is async) so the deploy
    # ssh returns immediately instead of hanging on "Pending job threshold reached. Retrying in 60s" under a
    # saturated pending-job quota. See star_deploy.submit_star_over_ssh for the full rationale.
    _lo = shq(bed_root + '/launch.out')
    launch = (
        f"( setsid bsub -L /bin/bash -n 1 -M 1000 -W 66480 -J {shq(bed_tag + '_launch')} "
        f"-o {_lo} -e {shq(bed_root + '/launch.err')} {shq(bed_root + '/bed_launch.sh')} "
        f"</dev/null >>{_lo} 2>&1 & )"
    )
    if prior_skipped:
        # START at BAM->BED (STAR skipped): the launcher polls <BAM_OUT>/PIPELINE_COMPLETE.txt, which no
        # STAR run will write -> pre-create it so BED runs NOW on the BAMs the user already placed in BAM_OUT.
        _bo = bam_out_root.rstrip("/")
        launch = f"mkdir -p {shq(_bo)} && touch {shq(_bo + '/PIPELINE_COMPLETE.txt')}; " + launch
        print(f"  BED SUBMIT: STAR skipped -> pre-touch {_bo}/PIPELINE_COMPLETE.txt (no-wait start)")
    print(f"=== BED SUBMIT: {user}@{host}:{port} -> {bed_root} ===")
    try:
        if password:
            try:
                import paramiko  # noqa: F401
            except Exception:
                raise RuntimeError("password auth needs paramiko (pip install paramiko) or use an SSH key")
            res = cluster_deploy._submit_paramiko(P, host, port, user, password, keyfile, bed_root,
                                                  reporter, src_dir=P.bed_dir, launch_cmd=launch)
        else:
            res = cluster_deploy._submit_systemssh(P, host, port, user, keyfile, bed_root,
                                                   reporter, src_dir=P.bed_dir, launch_cmd=launch)
        # guard: the submit helpers return {"submitted": True, ...} only on success (they raise otherwise),
        # but never report submitted=True if the result doesn't actually confirm the launch.
        if not (isinstance(res, dict) and res.get("submitted")):
            reason = (res or {}).get("reason", "submit did not confirm launch") if isinstance(res, dict) else "submit did not confirm launch"
            print(f"  BED SUBMIT: launch not confirmed -> {reason}")
            return {"submitted": False, "reason": reason,
                    "diagnosis": cluster_deploy.diagnose_failure("", reason)}
        # ship the heavy exon ref AFTER the bundle upload, so <bed_root>/altanalyze already exists and the
        # refs/ merges cleanly into it (no scp -r nesting). Non-fatal: the launcher self-heals (retries)
        # if the ref isn't there yet, and STAR is still running so there is time to spare.
        try:
            _upload_ref_idempotent(host, port, user, keyfile, password, bed_root, species, reporter)
        except Exception as ref_err:
            print(f"  BED SUBMIT: exon-ref upload failed ({ref_err}) -> launcher will retry; "
                  "upload the ref manually if it persists")
        print(f"  BED SUBMIT: self-rescheduling launcher armed on {host} — BED starts on the cluster "
              "when STAR finishes (safe to close SpliceScout now)")
        return res
    except Exception as e:
        output = getattr(e, "output", "") or str(e)
        diag = cluster_deploy.diagnose_failure(output, str(e))
        print(f"  BED SUBMIT FAILED: {e}  -> {diag['title']}")
        print("  -> the BED bundle is still downloadable (RUN_BED_ON_CLUSTER.txt).")
        reporter.set_detail(f"BED submit failed: {diag['title']}")
        return {"submitted": False, "reason": str(e), "diagnosis": diag}
